### ISSUE TITLE
Funcionalidade para facilitar manipulação das premissas

### ISSUE THREAD

**Issue by crotman** [EPE-GOV-BR/epe4md#21]
Poderia haver uma função epe4md_copia_premissas(destino) para copiar os arquivos de premissas para um novo diretório onde eles possam ser alterados e depois usados como premissas alteradas. 

Hoje o usuário precisa se aventurar pelos diretórios de instalação do pacote

**Comment by gabrielkonzen** [comment]
Criei a função epe4md_copia_premissas
