### ISSUE TITLE
Dados Premissas PLAN/2024-2028

### ISSUE THREAD

**Issue by carneirogoulart** [EPE-GOV-BR/epe4md#35]
Bom dia!

Os dados de premissas para expansão da MMGD utilizada no PLAN/2024-2028 será disponibilizada?

**Comment by gabrielkonzen** [comment]
Olá. Já foi publicado como um release do pacote. https://github.com/EPE-GOV-BR/epe4md/releases/tag/vPLAN-2024-2028
